#!/bin/bash


echo "start embedding"

name=../data/subject_1_block_$1_rawtext.txt
echo "$name"

var=$(< $name)
echo "$var"


 python lm_1b_eval.py --mode dump_lstm_emb --pbtxt ../data/graph-2016-09-10.pbtxt --vocab_file ../data/vocab-2016-09-10.txt --ckpt '../checkpoints/ckpt-*' --save_dir ../output/subject_1_block_$1_lstm_0_embeddings  --sentence "$var"

echo "Done :)"
