#!/bin/bash


echo "start word embedding"

python lm_1b_eval.py --mode dump_emb --pbtxt ../data/graph-2016-09-10.pbtxt --vocab_file ../new_input/subject_$1_harry_potter_vocab.txt --ckpt '../checkpoints/ckpt-*' --save_dir ../new_output/subject_$1/

echo "Done :)"
